//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.HBlazorApp.DataLayer.DataEntries.Common;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class ApplicationSettingsEntries : Havit.Data.Patterns.DataEntries.DataEntries<MB.HBlazorApp.Model.Common.ApplicationSettings>, IApplicationSettingsEntries 
{
	private MB.HBlazorApp.Model.Common.ApplicationSettings current;

	public MB.HBlazorApp.Model.Common.ApplicationSettings Current => current ??= GetEntry(MB.HBlazorApp.Model.Common.ApplicationSettings.Entry.Current);

	public ApplicationSettingsEntries(MB.HBlazorApp.DataLayer.Repositories.Common.IApplicationSettingsRepository repository)
		: base(repository)
	{
	}
}
