//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.HBlazorApp.DataLayer.DataEntries.Localizations;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class LanguageEntries : Havit.Data.Patterns.DataEntries.DataEntries<MB.HBlazorApp.Model.Localizations.Language>, ILanguageEntries 
{
	private MB.HBlazorApp.Model.Localizations.Language czech;
	private MB.HBlazorApp.Model.Localizations.Language english;

	public MB.HBlazorApp.Model.Localizations.Language Czech => czech ??= GetEntry(MB.HBlazorApp.Model.Localizations.Language.Entry.Czech);
	public MB.HBlazorApp.Model.Localizations.Language English => english ??= GetEntry(MB.HBlazorApp.Model.Localizations.Language.Entry.English);

	public LanguageEntries(MB.HBlazorApp.DataLayer.Repositories.Localizations.ILanguageRepository repository)
		: base(repository)
	{
	}
}
